# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b34193fab73498b17e9314569294bbdb67cd85fc18f6c1ae02034cfb1f33fef508b8947920abc1dfc2fe11dac8d0c0c83909b37c809068607d8e80477f6de07c

test:
  secret_key_base: 3497aac337bc0dfa6c1d297edf22fd949acd6494d3da375c0f53f1f2bbaf0c934e0105c57bf0784ae355442d3da0095c72e9fd6b4a050a2519d57fc92cbe8d82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
